### ISSUE TITLE
Question: typical execution time time for motion correction?

### ISSUE THREAD

**Issue by jsheunis** [jeffmacinnes/pyneal#5]
Hi @jeffmacinnes 

Thanks for your great work on pyneal and for making it open source. Working in real-time fMRI methods and having recently started moving over to Python, this has helped me a lot.

A colleague and I are now implementing a real-time fMRI processing and visualisation tool in Python and have used your realignment algorithm, but we’re experiencing challenges with the execution time of realignment for a single volume. The first test took almost 1000 ms to run for what should be a straightforward realignment procedure (no excessive motion) on standard data (NIfTI volumes, in plane matrix size 64x64, isotropic 3mm voxels). This was on a laptop with adequate processing power. Comparably, my existing Matlab code using SPM12 realignment (based on the OpenNFT implementation) could do the same step in less than 200ms.

Specifically the `reg.optimize()` line in the `estimateMotion()` function takes the longest to execute. We have tried different optimizers and the `cg` option seems to give the best results (about 300ms for that line to run), but we're unsure what implications this might have for the realignment procedure.

Did you go through similar challenges when testing pyneal functionality? What execution time do you typically get for the pyneal motion correction step? Do you have suggestions for what we could look into in order to improve our performance?

**Comment by jeffmacinnes** [comment]
Hi @jsheunis -- 

That estimation time seems a bit high, but in the ballpark of what I've experienced as well. For comparison, it typically takes ~500-750ms per vol with 64x64x18 volume.

As you probably noticed in the code, the motion estimation uses [HistogramRegistration](https://github.com/nipy/nipy/blob/master/nipy/algorithms/registration/histogram_registration.py) from the Nipy library. I haven't spent much time trying to optimize it, but would love to hear if you make any progress on that front. 

Cheers!

**Comment by jsheunis** [comment]
Thanks for the response!

Us neither, but will be looking into it over the coming weeks and I'll keep you updated.

**Comment by jsheunis** [comment]
Hi Jeff. I wrote up some code to test different optimization options for the `optimize` method of `HistogramRegistration`. I encountered some challenges and [asked about it on NeuroStars](https://neurostars.org/t/testing-different-optimizer-options-in-nipys-histogramregistration/5281), if you're interested.
